
# New SYDPOWER Local MQTT API
API_BASE_URL = "https://api.app.sydpower.com/http/router/client/device"
API_GET_DEVICE_LIST = f"{API_BASE_URL}/saas.pub_getDeviceList"
API_UPDATE_MQTT_STATE = f"{API_BASE_URL}/saas.pub_updateMqttState"

# Default MQTT port for local broker
DEFAULT_MQTT_PORT = 1883

# Register definitions
REGISTER_MODBUS_ADDRESS = 17
REGISTER_TOTAL_INPUT = 6
REGISTER_DC_INPUT = 4
REGISTER_MAXIMUM_CHARGING_CURRENT = 20
REGISTER_USB_OUTPUT = 24
REGISTER_DC_OUTPUT = 25
REGISTER_AC_OUTPUT = 26
REGISTER_LED = 27
REGISTER_TOTAL_OUTPUT = 39
REGISTER_ACTIVE_OUTPUT_LIST = 41
REGISTER_STATE_OF_CHARGE = 56
REGISTER_AC_SILENT_CHARGING = 57
REGISTER_USB_STANDBY_TIME = 59
REGISTER_AC_STANDBY_TIME = 60
REGISTER_DC_STANDBY_TIME = 61
REGISTER_SCREEN_REST_TIME = 62
REGISTER_STOP_CHARGE_AFTER = 63
REGISTER_DISCHARGE_LIMIT = 66
REGISTER_CHARGING_LIMIT = 67
REGISTER_SLEEP_TIME = 68
