
# API Settings
ENDPOINT = "https://api.next.bspapp.com/client"
CLIENT_SECRET = "5rCEdl/nx7IgViBe4QYRiQ=="

# MQTT Settings
MQTT_HOST_PROD = "mqtt.sydpower.com"
MQTT_HOST_DEV = "dev.mqtt.sydpower.com"
MQTT_PORT = 8083
MQTT_CLIENT_ID_PREFIX = "client_helloyou"
MQTT_PASSWORD = "helloyou"
MQTT_WEBSOCKET_PATH = "/mqtt"

# Register definitions
REGISTER_MODBUS_ADDRESS = 17
REGISTER_TOTAL_INPUT = 6
REGISTER_DC_INPUT = 4
REGISTER_MAXIMUM_CHARGING_CURRENT = 20
REGISTER_USB_OUTPUT = 24
REGISTER_DC_OUTPUT = 25
REGISTER_AC_OUTPUT = 26
REGISTER_LED = 27
REGISTER_TOTAL_OUTPUT = 39
REGISTER_ACTIVE_OUTPUT_LIST = 41
REGISTER_STATE_OF_CHARGE = 56
REGISTER_AC_SILENT_CHARGING = 57

# Logger Settings
DEFAULT_LOG_LEVEL = "DEBUG"  # Can be DEBUG, INFO, WARNING, ERROR
LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"